---
# handlers file for tomcat
  - name: Stop tomcat services
    shell: /opt/tomcat1/apache-tomcat-{{tomcat_version}}/bin/shutdown.sh

  - name: Start Tomcat on sever
    shell: nohup /opt/tomcat1/apache-tomcat-{{tomcat_version}}/bin/startup.sh
